[package]
name = "purple_elephant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "=1.17.17"

[lib]
name = "purple_elephant"
crate-type = ["cdylib", "lib"]